# Generated by Django 2.2.10 on 2020-05-08 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('date_start', models.DateTimeField(default=datetime.datetime(2020, 5, 8, 11, 53, 23, 45749), verbose_name='Дата публикации')),
                ('date_close', models.DateTimeField(verbose_name='Дата окончания')),
                ('text_question', models.TextField(max_length=255, verbose_name='Текст опроса')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
    ]
