# Generated by Django 2.2.10 on 2020-05-08 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200508_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_id', to='app.Question', verbose_name='Опросы:'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 16, 7, 39, 570431), verbose_name='Дата публикации'),
        ),
        migrations.CreateModel(
            name='QuestionBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255, verbose_name='Текст вопроса')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='app.User', verbose_name='Опрашиваемый пользователь:')),
            ],
        ),
    ]
