# Generated by Django 2.2.10 on 2020-05-08 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200508_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionbody',
            options={'verbose_name': 'Конструктор опросов', 'verbose_name_plural': 'Конструкторы опросов'},
        ),
        migrations.AddField(
            model_name='questionbody',
            name='choice',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbody',
            name='choice_type',
            field=models.CharField(choices=[('1', 'Ответ текстом'), ('2', 'Ответ с выбором одного варианта'), ('3', 'Ответ с выбором нескольких вариантов')], default='10', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 17, 1, 37, 195643), verbose_name='Дата публикации'),
        ),
    ]
