# Generated by Django 2.2.10 on 2020-05-09 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200508_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbody',
            name='question',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text_question',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='votes',
        ),
        migrations.AlterField(
            model_name='question',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 10, 11, 7, 1621), verbose_name='Дата публикации'),
        ),
        migrations.DeleteModel(
            name='QuestionBody',
        ),
    ]
